"""d1_users_and_auth

Revision ID: 18ee088c70a1
Revises: 
Create Date: 2026-08-05 22:23:34.126644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18ee088c70a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('correo_institucional', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('pending_profile', 'pending_approval', 'active', 'rejected', name='userstatus', native_enum=False, length=20), nullable=False),
    sa.Column('perfil', sa.Enum('analista', 'modelador', 'integrador', name='userprofile', native_enum=False, length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_estado'), 'users', ['estado'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_numero_cuenta'), 'users', ['numero_cuenta'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_numero_cuenta'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_estado'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
