"""Add tema and numero to DailyExercise

Revision ID: 2175716037d7
Revises: 5c0ba8879b0f
Create Date: 2026-08-25 23:36:12.234614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2175716037d7'
down_revision: Union[str, None] = '5c0ba8879b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_exercises', sa.Column('tema', sa.String(length=255), server_default='General', nullable=False))
    op.add_column('daily_exercises', sa.Column('numero', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_exercises', 'numero')
    op.drop_column('daily_exercises', 'tema')
    # ### end Alembic commands ###
