"""d1_add_user_pronombres

Revision ID: 5319065b8dcc
Revises: 18ee088c70a1
Create Date: 2026-08-05 23:39:11.326840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5319065b8dcc'
down_revision: Union[str, None] = '18ee088c70a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Se agrega con server_default para poblar filas existentes; el default
    # sigue aplicando a nuevos INSERTs también, pero el modelo lo cubre.
    op.add_column(
        'users',
        sa.Column(
            'pronombres',
            sa.Enum('ella', 'el', 'elle', 'prefiero_no_decir', name='userpronouns', native_enum=False, length=20),
            nullable=False,
            server_default='prefiero_no_decir',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pronombres')
    # ### end Alembic commands ###
