"""Replace WebAssign with DailyExercises

Revision ID: 5c0ba8879b0f
Revises: eee6faec01de
Create Date: 2026-08-25 22:25:38.376925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '5c0ba8879b0f'
down_revision: Union[str, None] = 'eee6faec01de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_exercises_fecha'), 'daily_exercises', ['fecha'], unique=True)
    op.add_column('streak_evidence', sa.Column('daily_exercise_id', sa.Integer(), nullable=True))
    op.add_column('streak_evidence', sa.Column('solucion_path', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'streak_evidence', 'daily_exercises', ['daily_exercise_id'], ['id'])
    op.drop_column('streak_evidence', 'captura_path')
    op.drop_column('streak_evidence', 'webassign_report_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streak_evidence', sa.Column('webassign_report_url', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('streak_evidence', sa.Column('captura_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'streak_evidence', type_='foreignkey')
    op.drop_column('streak_evidence', 'solucion_path')
    op.drop_column('streak_evidence', 'daily_exercise_id')
    op.drop_index(op.f('ix_daily_exercises_fecha'), table_name='daily_exercises')
    op.drop_table('daily_exercises')
    # ### end Alembic commands ###
