"""d3_economy_ledger_and_catalog

Revision ID: 98d19bcd4ae5
Revises: adaf48c0895a
Create Date: 2026-08-06 21:45:00.362151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98d19bcd4ae5'
down_revision: Union[str, None] = 'adaf48c0895a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privilege_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('es_grupal', sa.Boolean(), nullable=False),
    sa.Column('limites_config', sa.JSON(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('feature_flag_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('decimal_redemption_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entrega_descripcion', sa.String(length=200), nullable=False),
    sa.Column('entrega_ref', sa.String(length=50), nullable=True),
    sa.Column('decimas_solicitadas', sa.Integer(), nullable=False),
    sa.Column('pts_costo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='decimalrequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('nota_profesor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decimal_redemption_requests_estado'), 'decimal_redemption_requests', ['estado'], unique=False)
    op.create_index(op.f('ix_decimal_redemption_requests_user_id'), 'decimal_redemption_requests', ['user_id'], unique=False)
    op.create_table('privilege_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio', sa.String(length=24), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('costo_total', sa.Integer(), nullable=False),
    sa.Column('pagado_total', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('funding', 'emitted', 'consumed', 'cancelled', 'expired', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('emitido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumido_por_admin_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['privilege_catalog.id'], ),
    sa.ForeignKeyConstraint(['consumido_por_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privilege_tickets_estado'), 'privilege_tickets', ['estado'], unique=False)
    op.create_index(op.f('ix_privilege_tickets_folio'), 'privilege_tickets', ['folio'], unique=True)
    op.create_index('ix_tickets_estado_catalog', 'privilege_tickets', ['estado', 'catalog_id'], unique=False)
    op.create_table('token_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.Enum('practica', 'racha', 'hito_racha', 'licitacion', 'sustentacion_destacada', 'post_destacado', 'kudos_out', 'kudos_in', 'ajuste_admin', 'canje_privilegio', 'canje_decima', 'split_bill_refund', 'bono_manual', name='tokensource', native_enum=False, length=30), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=30), nullable=True),
    sa.Column('referencia_id', sa.BigInteger(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_user_created', 'token_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_ledger_created_at'), 'token_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_ledger_fuente'), 'token_ledger', ['fuente'], unique=False)
    op.create_index(op.f('ix_token_ledger_user_id'), 'token_ledger', ['user_id'], unique=False)
    op.create_table('split_bill_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['privilege_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_split_contrib_ticket_user', 'split_bill_contributions', ['ticket_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_split_contrib_ticket_user', table_name='split_bill_contributions')
    op.drop_table('split_bill_contributions')
    op.drop_index(op.f('ix_token_ledger_user_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_fuente'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_created_at'), table_name='token_ledger')
    op.drop_index('ix_ledger_user_created', table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_index('ix_tickets_estado_catalog', table_name='privilege_tickets')
    op.drop_index(op.f('ix_privilege_tickets_folio'), table_name='privilege_tickets')
    op.drop_index(op.f('ix_privilege_tickets_estado'), table_name='privilege_tickets')
    op.drop_table('privilege_tickets')
    op.drop_index(op.f('ix_decimal_redemption_requests_user_id'), table_name='decimal_redemption_requests')
    op.drop_index(op.f('ix_decimal_redemption_requests_estado'), table_name='decimal_redemption_requests')
    op.drop_table('decimal_redemption_requests')
    op.drop_table('privilege_catalog')
    # ### end Alembic commands ###
