"""d2_teams_and_name_proposals

Revision ID: adaf48c0895a
Revises: 5319065b8dcc
Create Date: 2026-08-06 21:01:16.223620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adaf48c0895a'
down_revision: Union[str, None] = '5319065b8dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_firma', sa.String(length=40), nullable=True),
    sa.Column('estado_nombre', sa.Enum('pendiente', 'aprobado', 'asignado_por_sistema', name='teamnamestatus', native_enum=False, length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_firma')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_members_team_active', 'team_members', ['team_id', 'left_at'], unique=False)
    op.create_index('ix_team_members_user_active', 'team_members', ['user_id', 'left_at'], unique=False)
    op.create_table('team_name_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('propuesta', sa.String(length=40), nullable=False),
    sa.Column('propuesto_por', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente_mod', 'aprobado', 'rechazado', 'superseded', name='proposalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('nota_moderacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propuesto_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_name_proposals_estado'), 'team_name_proposals', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name_proposals_estado'), table_name='team_name_proposals')
    op.drop_table('team_name_proposals')
    op.drop_index('ix_team_members_user_active', table_name='team_members')
    op.drop_index('ix_team_members_team_active', table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
