"""iter1_content_and_streak

Revision ID: de29d7d6d06f
Revises: 2dad9acd79a5
Create Date: 2026-08-17 21:52:21.947924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de29d7d6d06f'
down_revision: Union[str, None] = '2dad9acd79a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('course_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('numero_sesion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=False),
    sa.Column('apuntes_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('notion_last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'numero_sesion', name='uq_session_module_numero'),
    sa.UniqueConstraint('notion_page_id')
    )
    op.create_table('streak_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('completado', 'fallido', 'neutro', 'pase_aplicado', name='streakdaystatus', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fecha', name='uq_streak_day_user_fecha')
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('es_anonimo_para_pares', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_parent_post_id'), 'forum_posts', ['parent_post_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_session_id'), 'forum_posts', ['session_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_user_id'), 'forum_posts', ['user_id'], unique=False)
    op.create_table('streak_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('streak_day_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('webassign_report_url', sa.String(length=500), nullable=False),
    sa.Column('captura_path', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['streak_day_id'], ['streak_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('streak_day_id')
    )
    op.create_index(op.f('ix_streak_evidence_user_id'), 'streak_evidence', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No se hace `drop_index` explícito de los índices que respaldan un FK
    # (ix_streak_evidence_user_id, ix_forum_posts_user_id/session_id/
    # parent_post_id) antes del drop_table correspondiente: MySQL/InnoDB
    # rechaza soltar un índice que todavía respalda un FK. `drop_table` se
    # lleva el índice y el FK juntos sin ese problema.
    op.drop_table('streak_evidence')
    op.drop_table('forum_posts')
    op.drop_table('streak_days')
    op.drop_table('course_sessions')
    op.drop_table('modules')
    # ### end Alembic commands ###
