"""Add pendiente_revision to StreakDayStatus

Revision ID: eee6faec01de
Revises: f4a2d8c19e6b
Create Date: 2026-08-25 21:23:35.795121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eee6faec01de'
down_revision: Union[str, None] = 'f4a2d8c19e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
