"""d4_inbox_announcements_system

Revision ID: f28e6bc07eca
Revises: 98d19bcd4ae5
Create Date: 2026-08-09 18:12:37.743990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f28e6bc07eca'
down_revision: Union[str, None] = '98d19bcd4ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('cuerpo_md', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.Enum('normal', 'alta', name='announcementpriority', native_enum=False, length=10), nullable=False),
    sa.Column('anclado', sa.Boolean(), nullable=False),
    sa.Column('alcance_tipo', sa.Enum('todos', 'equipo', 'alumno', name='announcementscope', native_enum=False, length=10), nullable=False),
    sa.Column('alcance_ids', sa.JSON(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('publicado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcements_activo_anclado', 'announcements', ['activo', 'anclado'], unique=False)
    op.create_table('inbox_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('registro', 'nombre_firma', 'canje_decima', 'disputa', 'sancion', 'feedback_sospechoso', 'sustentacion_destacada_pendiente', 'post_destacado_pendiente', 'alerta_inactividad', 'alerta_sistema', name='inboxitemtype', native_enum=False, length=40), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('prioridad', sa.Enum('alta', 'media', 'baja', name='inboxpriority', native_enum=False, length=10), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'atendido', 'pospuesto', 'descartado', 'visto', name='inboxitemstatus', native_enum=False, length=15), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.Column('nota_resolucion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resuelto_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbox_estado_prioridad', 'inbox_items', ['estado', 'prioridad'], unique=False)
    op.create_index(op.f('ix_inbox_items_estado'), 'inbox_items', ['estado'], unique=False)
    op.create_index(op.f('ix_inbox_items_tipo'), 'inbox_items', ['tipo'], unique=False)
    op.create_index('ix_inbox_tipo_referencia', 'inbox_items', ['tipo', 'referencia_id'], unique=False)
    op.create_table('system_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('announcement_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcement_reads_unique', 'announcement_reads', ['announcement_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_announcement_reads_unique', table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_table('system_flags')
    op.drop_index('ix_inbox_tipo_referencia', table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_tipo'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_estado'), table_name='inbox_items')
    op.drop_index('ix_inbox_estado_prioridad', table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index('ix_announcements_activo_anclado', table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('system_state')
    # ### end Alembic commands ###
